### ISSUE TITLE
Remember authentication state in browser extension

### ISSUE THREAD

**Issue by filiphorvei** [olaven/paperpod#182]
The Chrome extension (haven't tried Firefox) forgets me after a short while, and I have to sign in again.

**Comment by olaven** [comment]
Do you know ~ how long "a short while" is? Are we talking more than 15 minutes?
This is caused by expiry dates on the JWT-tokens.

I've scheduled to look into this and will probably increase the expiry by quite a bit.
UX is more important here :-)
